export const LOADING_DATA = 'loading'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_LOGIN_LOADING = 'USER_LOGIN_LOADING'
export const USER_LOGIN_LOADING_APPLE = 'USER_LOGIN_LOADING_APPLE'
export const USER_LOGIN_SUCCESS = 'user-login-success'
export const USER_LOGIN_ERROR = 'user-login-error'
export const USER_RGISTER_SUCCESS = 'USER_RGISTER_SUCCESS'
export const USER_RGISTER_ERROR = 'USER_RGISTER_ERROR'
export const USER_LOGIN_CLEAR = 'USER_LOGIN_CLEAR'
export const USER_UPDATE_SUCCESS = 'user-update-success'
export const REMOVE_OPENTOK_TOKEN = 'REMOVE_OPENTOK_TOKEN'

export const DELETE_PROFILE_LOADING = 'DELETE_PROFILE_LOADING'
export const DELETE_PROFILE_ERROR = 'DELETE_PROFILE_ERROR'
export const DELETE_PROFILE_SUCCESS = 'DELETE_PROFILE_SUCCESS'

export const USER_SIGNUP_BLANK = 'USER_SIGNUP_BLANK'
export const USER_SIGNUP_LOADING = 'USER_SIGNUP_LOADING'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'

export const GET_PROFILE_LOADING = 'GET_PROFILE_LOADING'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

export const UPDATE_PROFILE_LOADING = 'UPDATE_PROFILE_LOADING'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'

export const CLEAR_CART = 'CLEAR_CART'
export const GET_CART_LOADING = 'GET_CART_LOADING'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_ERROR = 'GET_CART_ERROR'
export const ADD_CART_ITEM = 'ADD_CART_ITEM'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM'
export const ADD_NEW_CART_ITEM_SUCCESS = 'ADD_NEW_CART_ITEM_SUCCESS'
export const ADD_LOCAL_NEW_CART_ITEM_SUCCESS = 'ADD_LOCAL_NEW_CART_ITEM_SUCCESS'
export const ADD_NEW_CART_ITEM_ERROR = 'ADD_NEW_CART_ITEM_ERROR'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS'
export const DELETE_CART_ITEM_ERROR = 'DELETE_CART_ITEM_ERROR'
export const DELETE_LOCAL_CART_ITEM = 'DELETE_LOCAL_CART_ITEM'
export const ADD_NEW_FAVORITE_ITEM = 'ADD_NEW_FAVORITE_ITEM'
export const DELETE_FAVORITE_ITEM = 'DELETE_FAVORITE_ITEM'
export const APPLY_FILTER_SUCCESS = 'APPLY_FILTER_SUCCESS'
export const APPLY_FILTER_ERROR = 'APPLY_FILTER_ERROR'

export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_LODING = 'CHECKOUT_LODING'
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR'
export const FINISH_CHECKOUT = 'FINISH_CHECKOUT'

export const PLACE_ORDER_LOADING = 'PLACE_ORDER_LOADING'
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR'

export const GET_SELLING_LIST_LOADING = 'GET_SELLING_LIST_LOADING'
export const GET_SELLING_LIST_SUCCESS = 'GET_SELLING_LIST_SUCCESS'
export const GET_SELLING_LIST_ERROR = 'GET_SELLING_LIST_ERROR'
export const GET_PURCHASED_LIST_SUCCESS = 'GET_PURCHASED_LIST_SUCCESS'
export const GET_PURCHASED_LIST_ERROR = 'GET_PURCHASED_LIST_ERROR'
export const GET_SELLING_ITEM_DETAIL_LOADING = 'GET_SELLING_ITEM_DETAIL_LOADING'
export const GET_SELLING_ITEM_DETAIL_SUCCESS = 'GET_SELLING_ITEM_DETAIL_SUCCESS'
export const GET_SELLING_ITEM_DETAIL_ERROR = 'GET_SELLING_ITEM_DETAIL_ERROR'

export const GET_LISTING_DETAILS_SUCCESS = 'GET_LISTING_DETAILS_SUCCESS'
export const GET_LISTING_DETAILS_LOADING = 'GET_LISTING_DETAILS_LOADING'
export const GET_LISTING_DETAILS_ERROR = 'GET_LISTING_DETAILS_ERROR'

export const SELLER_CONFIRM_ORDER_SUCCESS = 'SELLER_CONFIRM_ORDER_SUCCESS'
export const SELLER_CONFIRM_ORDER_LOADING = 'SELLER_CONFIRM_ORDER_LOADING'
export const SELLER_CONFIRM_ORDER_ERROR = 'SELLER_CONFIRM_ORDER_ERROR'

export const SELLER_CANCEL_ORDER_SUCCESS = 'SELLER_CANCEL_ORDER_SUCCESS'
export const SELLER_CANCEL_ORDER_LOADING = 'SELLER_CANCEL_ORDER_LOADING'
export const SELLER_CANCEL_ORDER_ERROR = 'SELLER_CANCEL_ORDER_ERROR'

export const BUYER_CANCEL_ORDER_SUCCESS = 'BUYER_CANCEL_ORDER_SUCCESS'
export const BUYER_CANCEL_ORDER_LOADING = 'BUYER_CANCEL_ORDER_LOADING'
export const BUYER_CANCEL_ORDER_ERROR = 'BUYER_CANCEL_ORDER_ERROR'

export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS'
export const GET_ORDER_DETAIL_LOADING = 'GET_ORDER_DETAIL_LOADING'
export const GET_ORDER_DETAIL_ERROR = 'GET_ORDER_DETAIL_ERROR'
export const GET_ORDER_DETAIL_LIST_LOADING = 'GET_ORDER_DETAIL_LSIT_LOADING'
export const GET_ORDER_DETAIL_LIST_SUCCESS = 'GET_ORDER_DETAIL_LIST_SUCCESS'
export const GET_ORDER_DETAIL_LIST_ERROR = 'GET_ORDER_DETAIL_LIST_ERROR'

export const GET_BUYER_ORDER_DETAIL_LIST_SUCCESS =
  'GET_BUYER_ORDER_DETAIL_LIST_SUCCESS'
export const GET_BUYER_ORDER_DETAIL_LIST_LOADING =
  'GET_BUYER_ORDER_DETAIL_LIST_LOADING'
export const GET_BUYER_ORDER_DETAIL_LIST_ERROR =
  'GET_BUYER_ORDER_DETAIL_LIST_ERROR'

export const UPDATE_SELLING_ITEM_LOADING = 'UPDATE_SELLING_ITEM_LOADING'
export const UPDATE_SELLING_ITEM_SUCCESS = 'UPDATE_SELLING_ITEM_SUCCESS'
export const UPDATE_SELLING_ITEM_ERROR = 'UPDATE_SELLING_ITEM_ERROR'

export const ADD_NEW_BUNNDLE = 'ADD_NEW_BUNNDLE'
export const DELETE_BUNDLE_ITEM = 'DELETE_BUNDLE_ITEM'
export const UPDATE_BUNDLE_ITEM = 'UPDATE_BUNDLE_ITEM'
export const PUBLISH_BUNDLE = 'PUBLISH_BUNDLE'
export const PUBLISH_BUNDLE_ERROR = 'PUBLISH_BUNDLE_ERROR'
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM'
export const ADD_NEW_ITEM_ERROR = 'ADD_NEW_ITEM_ERROR'
export const UNPUBLISH_BUNDLE = 'UNPUBLISH_BUNDLE'
export const UNPUBLISH_BUNDLE_ERROR = 'UNPUBLISH_BUNDLE_ERROR'
export const UNPUBLISH_BUNDLE_LOADING = 'UNPUBLISH_BUNDLE_LOADING'
export const ADD_PENDING_ITEM = 'ADD_PENDING_ITEM'

export const ADD_REVIEW = 'ADD_REVIEW'
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR'
export const ADD_REVIEW_LOADING = 'ADD_REVIEW_LOADING'

export const MARK_LISTING_RECEIVED = 'MARK_LISTING_RECEIVED'
export const MARK_LISTING_RECEIVED_LOADING = 'MARK_LISTING_RECEIVED_LOADING'
export const MARK_LISTING_RECEIVED_ERROR = 'MARK_LISTING_RECEIVED_ERROR'

export const UPDATE_LISTING_ITEM = 'UPDATE_LISTING_ITEM'
export const DELETE_LISTING_ITEM = 'DELETE_LISTING_ITEM'

export const GET_SHOP_LIST_LOADING = 'GET_SHOP_LIST_LOADING'
export const GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS'
export const GET_SHOP_LIST_ERROR = 'GET_SHOP_LIST_ERROR'

export const GET_PRODUCT_LIST_LOADING = 'GET_PRODUCT_LIST_LOADING'
export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS'
export const GET_PRODUCT_LIST_ERROR = 'GET_PRODUCT_LIST_ERROR'

export const STRIPE_CONNECTION_SUCCESS = 'STRIPE_CONNECTION_SUCCESS'
export const STRIPE_CONNECTED = 'STRIPE_CONNECTED'

export const GET_FILTER_DATA = 'FILTER_DATA'
export const GET_FILTER_DATA_ERROR = 'FILTER_DATA_ERROR'
export const GET_FILTER_DATA_LOADING = 'GET_FILTER_DATA_LOADING'
export const HISTORY_DATA = 'HISTORY_DATA'
export const CLEAR_HISTORY_DATA = 'CLEAR_HISTORY_DATA'
export const HISTORY_DATA_LOADING = 'HISTORY_DATA_LOADING'

export const EXPRESS_DASHBOARD = 'EXPRESS_DASHBOARD'
export const EXPRESS_DASHBOARD_LOADING = 'EXPRESS_DASHBOARD_LOADING'
export const EXPRESS_DASHBOARD_ERROR = 'EXPRESS_DASHBOARD_ERROR'

export const STRIPE_ACCOUNT_LINK = 'STRIPE_ACCOUNT_LINK'
export const STRIPE_ACCOUNT_LINK_LOADING = 'STRIPE_ACCOUNT_LINK_LOADING'
export const STRIPE_ACCOUNT_LINK_ERROR = 'STRIPE_ACCOUNT_LINK_ERROR'
export const STRIPE_BALANCE = 'STRIPE_BALANCE'
export const STRIPE_BALANCE_LOADING = 'STRIPE_BALANCE_LOADING'
export const STRIPE_BALANCE_ERROR = 'STRIPE_BALANCE_ERROR'

//Old
export const GET_ROOM_LIST_LOADING = 'GET_ROOM_LIST_LOADING'
export const GET_ROOM_LIST_SUCCESS = 'get-room-list-success'
export const GET_ROOM_LIST_ERROR = 'get-room-list-error'

export const CLEAR_IMAGE_DATA = 'GET_ROOM_LIST_LOADING'
export const CLEAR_IMAGE_ERROR = 'CLEAR_IMAGE_ERROR'
export const CLEAR_IMAGE_LOADING = 'CLEAR_IMAGE_LOADING'

export const PHONE_VERIFICATION_BLANK = 'PHONE_VERIFICATION_BLANK'
export const PUBLISHER_TOKEN_LOADING = 'PUBLISHER_TOKEN_LOADING'
export const PUBLISHER_TOKEN_SUCCESS = 'PUBLISHER_TOKEN_SUCCESS'
export const PUBLISHER_TOKEN_ERROR = 'PUBLISHER_TOKEN_ERROR'

export const SEND_VERIFICATION_CODE_SUCCESS = 'send-verification-code-success'
export const SEND_VERIFICATION_CODE_ERROR = 'send-verification-code-error'
export const VERIFY_VERIFICATION_CODE_SUCCESS =
  'verify-verification-code-success'
export const VERIFY_VERIFICATION_CODE_ERROR = 'verify-verification-code-error'

export const USER_FORGOT_LOADING = 'USER_FORGOT_LOADING'
export const USER_FORGOT_SUCCESS = 'USER_FORGOT_SUCCESS'
export const USER_FORGOT_ERROR = 'USER_FORGOT_ERROR'

export const PUSH_NOTIFICATION_LOADING = 'PUSH_NOTIFICATION_LOADING'
export const PUSH_NOTIFICATION_SUCCESS = 'PUSH_NOTIFICATION_SUCCESS'
export const PUSH_NOTIFICATION_ERROR = 'PUSH_NOTIFICATION_ERROR'

export const IMAGE_PROGRESS_LOADING = 'IMAGE_PROGRESS_LOADING'
export const IMAGE_PROGRESS_SUCCESS = 'IMAGE_PROGRESS_SUCCESS'
export const IMAGE_PROGRESS_ERROR = 'IMAGE_PROGRESS_ERROR'

export const REMOVE_BACKGROUND_LOADING = 'REMOVE_BACKGROUND_LOADING'
export const REMOVE_BACKGROUND_SUCCESS = 'REMOVE_BACKGROUND_SUCCESS'
export const REMOVE_BACKGROUND_ERROR = 'REMOVE_BACKGROUND_ERROR'

export const IMAGE_ID_LOADING = 'IMAGE_ID_LOADING'
export const IMAGE_ID_SUCCESS = 'IMAGE_ID_SUCCESS'
export const IMAGE_ID_ERROR = 'IMAGE_ID_ERROR'

export const RESET_BACKGROUNDIMAGE_STATE = 'RESET_BACKGROUNDIMAGE_STATE'
