export const brands = [
  '1901',
  '3 Sprouts',
  '3 Stories Trading',
  '3Doodler',
  '3Stories',
  '4D Master',
  '4moms',
  '5th and Ryder',
  '7 A.M. Enfant',
  'A Denim Story',
  'A Happy Brand',
  'A Little Lovely Company',
  'AB Home',
  'Absorba',
  'Accessory Innovations',
  'Acne JR',
  'Acne Studios',
  'Aden + Anais',
  'adidas',
  'AdTec',
  'AeroMoov',
  'AeroSleep',
  'Affenzahn',
  'Agatha Ruiz de la Prada',
  'AI Riders on the Storm',
  'Air Hogs',
  'Air Jordan',
  'AKID',
  'ALEX Toys',
  'Alexander McQueen',
  'Alga',
  'Alimrose',
  'ALIQUANTUM INTERNATIONAL INC',
  'American Culture',
  'American Tourister',
  'Amigo',
  'Amloid Corporation',
  'Amor Bebe',
  'Amscan',
  'Ancient Greek Sandals',
  'Andrew Marc',
  'Andy & Evan',
  'Angel of Sweden',
  'Angry Birds',
  'Angulus',
  'Animal Kingdom',
  'Anïve For The Minors',
  'Appaman',
  'Aquaplay',
  'Areyougame',
  'art & eden',
  'Art Park',
  'Artissimo Designs',
  'Asics',
  'Asweets',
  'Athena',
  'Ava & Yelly',
  'Avanchy',
  'Avengers',
  'Axkid',
  'Aykasa',
  'B Toys',
  'Babblarna',
  'Babiators',
  'Baby Alive',
  'Baby Annabell',
  'Baby Art',
  'Baby Aspen',
  'Baby Bling',
  'Baby Dan',
  'Baby Deer',
  'Baby Delight',
  'Baby Doppler',
  'Baby Jogger',
  "Baby K'tan",
  'Baby Mode',
  'Baby Tula',
  'BabyBjörn',
  'BabyBriefcase',
  'BabyDan',
  'Babymel',
  'Babymoov',
  'BABYZEN',
  'Badger Basket',
  'Badgley Mischka',
  'Baggallini',
  'Baghera',
  'Bajo',
  'Balmain',
  'Baltic',
  'BamBam',
  'Bambeado',
  'BAMBINO',
  'Bamse',
  "Bandit's Girl",
  'Banz',
  'Barbie',
  'Barbour',
  'Barcelona FC',
  'Bardot Junior',
  'Bari Lynn',
  'Barska',
  'Barts',
  'Basic Fun',
  'Baubles + Soles',
  'bbhugme',
  'BCBG',
  'BCX',
  'Be Good Company',
  'BÉABA',
  'Bear Camp',
  'BEARPAW',
  'Beatrix NY',
  'Beatrix Potter',
  'Beau & Rooster',
  'Beau Loves',
  'Beautees',
  'bebe',
  'Bébé au Lait',
  'Bebe-Jou',
  'Bebefit',
  'BedVoyage',
  'Beetle & Thread',
  'BeFreeSound',
  'Béis',
  'BELDINEST',
  'Bella Dahl',
  'Bella Tunno',
  'Belle de Mer',
  'Belle Du Jour',
  'Belle Isle Furniture',
  'BePuzzled',
  'Bergans',
  'Bernie Mev',
  'BeSafe',
  'Best Ride on Cars',
  'BEST TIME TOYS',
  'BESTAROO',
  'Bestway',
  'Beverly Hills Polo Club',
  'Bey-Berk',
  'Bibabad',
  'BIG',
  'Big Mouth Inc.',
  'Bigjigs Rail',
  'Bigjigs Toys',
  'BigMouth Inc',
  'Bigso Box of Sweden',
  'Billabong',
  'Billieblush',
  'Billionaire Boys Club',
  'BILLY Footwear',
  'Billybandit',
  'BIRDIE',
  'Birkenstock',
  'Bisgaard',
  'Bixbee',
  'Bjällra of Sweden',
  'Black Series',
  'Blafre',
  'Blaou',
  'Bleacher Creatures',
  'Bling2o',
  'Bloch',
  'Bloomingville',
  'Blue Orange Games',
  'Blue Wave',
  'Blueberi Boulevard',
  'Blune',
  'BLUSH by Us Angels',
  'BOB',
  'Bobo Choses',
  'Boden',
  'Bogner',
  'Bogs',
  'bokee',
  'Boker Laila',
  'Bolibompa',
  'Bollé',
  'Bonnie Baby',
  'Bonnie Jean',
  'Bonpoint',
  'Bontempi',
  'Bonton',
  'Boon',
  'Boppy',
  'Borås Cotton',
  'Born',
  'BOSS',
  'Boy London',
  'Boys & Girls',
  'BOZZ',
  'Bravado',
  'Breaking Waves',
  'BRIO',
  'Britax',
  'BubaBloon',
  'Buddy & Hope',
  'BudtzBendix',
  'Bugaboo',
  'búho',
  'Bumbo',
  'Bumkins',
  'Bumprider',
  'Bunnies by the Bay',
  'Burberry',
  "Burt's Bees Baby",
  'BuySeasons',
  'By Nils',
  'By On',
  'Cake Lingerie',
  'Cakewalk',
  'Calafant',
  'Calico',
  'Calisson',
  'Calvin Klein',
  'Cam Cam',
  'Camper',
  'Canada Goose',
  'Candide',
  'Candy Pink',
  'Capelli New York',
  'Capezio',
  'Capidi',
  'Caraa',
  "CARAN d'ACHE",
  'Cardinal Gates',
  'Carena',
  'Caroline Bosmans',
  'Carrément Beau',
  'Carriage Boutique',
  'Carriwell',
  "Carter's",
  'CasaCam',
  'Case IH',
  'Cassini',
  'Catimini',
  'CB Sports',
  'Cebe',
  'CeLaVi',
  'Centennial',
  'Chaco',
  'Champion',
  'ChangePal',
  'CHARM IT!',
  'Charter Club',
  'Cheeky Chompers',
  'Cheski Sock Company',
  'Chewbeads',
  'Chicco',
  'Child to Cherish',
  'Chillafish',
  'Chloé',
  'Christina Rohde',
  'Christmas Kids',
  'Chronicle Books',
  'Chubbies',
  'Ciao Charlie',
  'City Mouse',
  'Civiliants',
  'Clarks',
  'Classic World',
  'Classy Art',
  'Clek',
  'Close',
  'Cloud B',
  'Coffee Shop',
  'Colmar',
  'Colosseum',
  'Columbia',
  'Comfort',
  'Comme des Garçons PLAY',
  'Common Projects',
  'Comotomo',
  'Converse',
  'Cool Maker',
  'Copernicus',
  'Copper Pearl',
  'Cosabella Maternity',
  'Cosco',
  'Cosmo Brands',
  'Cotton Emporium',
  'COTTON ON',
  'Crane Air',
  'Crayola',
  'Crazy Forts',
  'Crckt',
  'Crea Bella',
  'Creamie',
  'Creative Baby',
  'Creative Whack Company',
  'crewcuts by J.Crew',
  'Crocodile Creek',
  'Crocs',
  'Cubcoats',
  'Cubika',
  'cuddle+kind',
  'Cuddlings',
  'Cybex',
  'Cyrillus',
  'Dance Class',
  'Danskin',
  'Dantoy',
  "Daphyl's",
  'David Charles',
  'David Yurman',
  'DAY et',
  'DC Comics',
  'DEER STAGS',
  'Delta Children',
  'Department 56',
  'Design Letters',
  'Dessy Collection',
  'Diadora',
  'Dickie Toys',
  'Dickies',
  'Didriksons',
  'Diesel',
  'Diggin Active',
  'DIONO',
  'Discovery Kids',
  'Disney',
  'Djeco',
  'DKNY',
  'DL1961',
  'DockATot',
  'Doddl',
  'Doddle & Co',
  'Dolce & Gabbana',
  'Dolly by Le Petit Tom',
  'Dondup',
  'Done by Deer',
  'Donsje Amsterdam',
  'Dooky',
  'DOOMOO',
  'Doona',
  'Dr Kid',
  'Dr. Martens',
  "DrBrown's",
  'Dreamwave',
  'Dsquared2',
  'Duncan',
  'DuneCraft',
  'Eastland Shoe',
  'Easy Peasy',
  'Easygrow',
  'EasyTots',
  'EasyWalker',
  'Eatsleepdoodle',
  'ebbe Kids',
  'Ecco',
  'Eco Viking',
  'Ecogear',
  'Educa',
  'Educational Insights',
  'Edushape',
  'eeBoo',
  'Egmont Kärnan',
  'eguchi toys',
  'Elegant Baby',
  'Eleven Paris',
  'Ellesse',
  'Elodie',
  'Elsa Beskow',
  'Elvie',
  'Elwood',
  "Ely's & Co.",
  'Emerald Sundae',
  'Emile et Ida',
  'Emile et Rose',
  'Emma och Malena',
  'Emmaljunga',
  'Emporio Armani',
  'EMSCO Group',
  'Emu Australia',
  'EN FANT',
  'Epic Threads',
  'Erbaviva',
  'Ergobaby',
  'ergoPouch',
  'Esprit',
  'Ethika',
  'Evenflo',
  'Evy of California',
  'EVY Technology',
  'ewatchfactory',
  'ExploreOne',
  'Eyes On Walls',
  'ezpz',
  'FAB',
  'Fabric Flavours',
  'Falke',
  'Family Games Inc.',
  'Fancy Nancy',
  'FantasEyes',
  'FAO Schwarz',
  'Fascinations',
  'Fashion Angels',
  'Fashion Plates',
  'Fat Brain Toys',
  'Fawn Design',
  'Fendi',
  'ferm LIVING',
  'Fifth Sun',
  'FILA',
  'Filemon Kid',
  'Filiokus',
  'Fin Fun',
  'Finlayson',
  'finn + emma',
  'First Impressions',
  'FIRST SEMESTER',
  'Fisher Price',
  'Fitbit',
  'Fixoni',
  'Fjällräven',
  'Flapdoodles',
  'Flexa Furniture',
  'Flo Dancewear',
  'Florsheim',
  'Focus Kids',
  'Footmates',
  'For All Seasons',
  'FORM Living',
  'Fossil',
  'FoxMind Games',
  'Frais',
  'Franco Manufacturing Co',
  'Franklin & Marshall',
  'Franklin Sports',
  'Fred & Friends',
  'Free 2 Dream',
  'Free Country',
  'French Toast',
  'Freshly Picked',
  'Freshman',
  'Fridababy',
  'Frozen',
  'Frugi',
  'FUB',
  'FUL',
  'Fundamental Toys',
  'Furniture',
  'Fusalp',
  'Galileo',
  'GANT',
  'GAP',
  'Garbo&Friends',
  'Garcia Jeans',
  'Gardner and the Gang',
  'GCDS',
  'Geggamoja',
  'Gener8',
  'Geomag',
  'GeoSmart',
  'Geospace',
  'Geox',
  'GigaTent',
  'Girl Power Sport',
  'Givenchy',
  'GlamBaby',
  'Glitter Beach',
  'Globber',
  'Globen Lighting',
  'GoBabyGo',
  'Golden Goose',
  'Golden Rabbit',
  'Goliath',
  'Good Lad',
  'Good Luck Girl',
  'Goodbaby',
  'Graco',
  'Gramicci',
  'Gray Label',
  'Green Toys',
  'Grom',
  'Group Sales',
  "Grow 'N Up",
  'Gucci',
  'GUESS',
  'Gugguu',
  'Guidecraft, Inc',
  'Gund',
  'Gymnic',
  'HABA',
  'Habitual',
  'Haggar',
  'Hallmark',
  'Halo',
  'Handstand Kitchen',
  'Hanes',
  'Hannah Banana',
  'Hansa',
  'Hape',
  'Happy Trails',
  'hari mari',
  'Harley Davidson',
  'Harry Potter',
  'Hart Schaffner Marx',
  'Hartmann',
  'Hasbro',
  'Hatchimals',
  'Hathaway',
  'Hatley',
  'Havaianas',
  'Hayden Girls',
  'Heart and Harmony',
  'Heelys',
  'HEICO',
  'Hello Kitty',
  'Helly Hansen',
  'Henri Lloyd',
  'Herobility',
  'Herschel',
  'Hevea',
  'Heys',
  'High IntenCity',
  'Hoberman',
  'Hobie',
  'Hog Wild',
  'Homeware',
  'Honeywell',
  'Honora',
  'HootKid',
  'Hot Wheels',
  'Hotel Collection',
  'House of Marbles',
  'How to Kiss a Frog',
  'Hudson',
  'Huffy',
  'Hugo Loves Tiki',
  'Humble Bee',
  'Hummel',
  'Hunter',
  'Hurley',
  'Hush Puppies',
  'Hust&Claire',
  'Huttelihut',
  'Hype',
  'I Dig Denim',
  'I Love My Type',
  'I See Me!',
  'Ia Bon',
  'iBaby',
  'Ideal',
  'Ideology',
  'IGH Global Corporation',
  'Igor',
  'IKKS',
  'Imperial Star',
  'INC International Concepts',
  'Indikidual',
  'INFANTECH',
  'Inovi',
  'Interdesign',
  'Intex',
  'Ipanema',
  'iPlay',
  'Iris & Ivy',
  'Isbjörn of Sweden',
  'Iscream',
  'Island Umbrella',
  'iTouch',
  'Itzy Ritzy',
  'IZIPIZI',
  'IZOD',
  'J.L. Childress',
  'Jabadabado',
  'Jack Rogers',
  'Jacques Moret Kids',
  'Jambu',
  'Janod',
  'Jay Franco',
  'Jay Imports',
  'JC Toys',
  'Jellycat',
  'Jem + Bea',
  'Jenny Yoo',
  'Jesse Lulu',
  'JLA Home',
  'Joah Love',
  'Jocko',
  "Joe's",
  'Joha',
  'John N. Hansen Co.',
  'johnnie-O',
  'Jojo Siwa',
  'Joolz',
  'Jordan',
  'Joseph Allen',
  'Josmo',
  'Jou Jou',
  'Joules',
  'JOX',
  'Ju-Ju-Be',
  'Juicy Couture',
  'Jurassic Park',
  'Just Dutch',
  'K-Swiss',
  'K-Way',
  'Kalencom',
  'Kaloo',
  'Kamik',
  'KAOS',
  'Kappa',
  'Karaoke USA',
  'Kardashian Kids',
  'Karl Lagerfeld Kids',
  'Kattnakken',
  'Kavat',
  'KeaBabies',
  'Keds',
  'keekaroo',
  'Keen',
  'Kenneth Cole',
  'Kensie Girl',
  'Kenzo',
  'KG Design',
  'Kickee Pants',
  'Kickers',
  'Kid Dangerous',
  'Kid O',
  "Kid's Concept",
  "Kid's Dough",
  'KidKraft',
  'Kidorable',
  'Kids Headquarters',
  'Kidscase',
  'Kidsme',
  'Kimba Kids',
  'Kind Culture Co.',
  'Kinderkind',
  'Kinetic Sand',
  'Kipling',
  'Kissy Kissy',
  'Klutz',
  'Kodak',
  'Koolabah',
  'Koolaburra By UGG',
  'Koziol',
  'KREA',
  'Kuling',
  'Kuling x Kenza',
  'Kunskapstavlan',
  'Kurt Adler',
  'L. Erickson',
  "L'ovedbaby",
  'La Perla',
  'LA PETITE HAYLEY PAIGE',
  'LA Pop Art',
  'Lacoste',
  'Laguna',
  'Lambs & Ivy',
  'Lamo',
  'Lanco',
  "Lands' End",
  'Lanoosh',
  'Larktale',
  'Lascal',
  'Lässig',
  'Laura Ashley',
  'Laura Ashley & Marmellata',
  'Lauren Madison',
  'Lauren Marie',
  'Lauren Ralph Lauren',
  'Le Big',
  'Le Chic',
  'Le Toy Van',
  'Learning Resources',
  'LEGO',
  'Lelin',
  'Lelli Kelly',
  'Lenox',
  'Les Coyotes De Paris',
  'Les Enfants',
  'Les Gamins',
  "Levi's",
  'Liewood',
  'Lifefactory',
  "Lil' Cub Hub",
  "Lil' Gleemerz",
  'Lila&Lucas',
  'Lilleba',
  'Lillelam',
  'Lillian Rose',
  'Lilly Pulitzer',
  'Lily Nily',
  "Lily's Island",
  'Lindberg',
  'Lipault',
  'Little Baby Bum',
  'Little Bird Told Me',
  'Little Brother by Pippa & Julie',
  'Little Creative Factory',
  'Little Giraffe',
  'Little Jalo',
  'Little Lambo',
  'Little LuWi',
  'Little Man Happy',
  'Little Marc Jacobs',
  'Little Marcel',
  'Little Me',
  'Little Pieces',
  'Little Remix',
  'Little Things Mean a Lot',
  'Little Tikes',
  'Little Treasure',
  'little unicorn',
  'Littlecodr Games Inc.',
  'Littleheart',
  'Littlephant',
  'Livie & Luca',
  'Living Textiles',
  'LIVLY',
  'Lladró',
  'LOL Surprise!',
  'Lola & the Boys',
  'Lolli Living',
  'Loloma',
  'London Fog',
  'Looney Tunes',
  'Loose Leaf Eyewear',
  'Lorena Canals',
  'Louis Louise',
  'Louise Misha',
  'Loulou Lollipop',
  'Lounge Buddies',
  'Love Boo',
  'Love, Fire',
  'Love, Nickie Lew',
  'LUCA AND CO',
  'Lucid Audio',
  'Lucky Brand',
  'Lucky Jade',
  'Lucy Darling',
  'Luli Bebé',
  'LULIBOX',
  'Lullaby Earth',
  'Lulu Jr.',
  'Lulujo',
  'Lulyboo',
  'Lundby',
  'LUNDMYR of Sweden',
  'Lush Décor',
  'Luvable Friends',
  'Lykkelig som liten',
  'Lyle & Scott',
  'M. Hidary',
  'Maaji',
  'Mac & Moon',
  'Maclaren',
  'Macmillan',
  "Macy's",
  'Made By Hands',
  'Magformers',
  'Magnetic Me',
  'Magnetic Poetry',
  'Maidenform',
  'Maileg',
  'Mainio',
  'Maison Labiche',
  'MAISON MANGOSTAN',
  'Majvillan',
  'MAM',
  'Mamalicious',
  'Manchester United',
  'Manhattan Toy',
  'Manière',
  'Maranda Enterprises, LLC',
  'Märklin',
  'MarMar Copenhagen',
  'Marni',
  'Marshmallow Fun Company',
  'Marvel',
  "Marvin's Magic",
  'Masterpieces Puzzles',
  'Matchbox',
  'Matchstick',
  'Mattel',
  'MAVERIX',
  'Max & Olivia',
  'Maxi Cosi',
  'Mayoral',
  'Maze Interior',
  'MC2 St Barth',
  'Me & Henry',
  'Me Too',
  'Medela',
  'MegaFun USA',
  'Mel by Melissa',
  'Melissa',
  'Melissa & Doug',
  'Melton',
  'Meri Meri',
  'Merrell',
  'Metal Xpressions',
  'Mi Amore Gigi',
  'Mia Chica',
  'MIA',
  'MiaMily',
  'Michael Kors',
  'Micki',
  'Micro',
  'Mifold',
  'Mignonette',
  'Miken',
  'Mikk-Line',
  'Miles',
  'Milestone',
  'mima',
  'Mimi & Lula',
  'MindWare',
  'Minecraft',
  'Mini A Ture',
  'Mini Boden',
  'Mini Kyomo',
  'Mini Melissa',
  'Mini Rodini',
  'Mini Sibling',
  'minimalisma',
  'Minna Parikka',
  'Minnetonka',
  'Minnie Mouse',
  'Mintini Baby',
  'Minymo',
  'Miracle Baby',
  'Mirella',
  'MissMiniMe',
  'MITTEEZ',
  'MLB LOGO',
  'MM of Sweden',
  'Moana',
  'MOBI',
  'MOBY',
  'Mohawk',
  'Mojo Licensing',
  'Molli Toys',
  'Molo',
  'Mom2Mom',
  'Mommy Power',
  'Moncler',
  'Money',
  'Monica + Andy',
  'Monkey Business Sports',
  'Monnalisa',
  'Monster Jam',
  'Monteau',
  'Moomin',
  'Moon Boot',
  'Moose Knuckles',
  'Mori',
  'Moschino',
  'Mother Trucker & co.',
  'Motormax',
  'Motorola',
  'Mou',
  'Moulin Roty',
  'Mountain And Isles',
  'Mountain Buggy',
  'MP',
  'Mr Maria',
  'MSGM',
  'Mud Pie',
  'Muddy Puddles',
  'MUDPUPPY',
  'Muk Luks',
  'Mukikim',
  'Mukkikim',
  'MUNCH MITT',
  'Munchkin',
  'Munki Munki',
  'Munsterkids',
  'Muurla',
  'My Little Artist',
  'My little day',
  'My Little Pony',
  'nadadelazos',
  'Najell',
  'Namoo',
  'Nanette Lepore',
  'Nanit',
  'Nao by Lladro',
  'National Geographic',
  'Native Shoes',
  'Nattou',
  'Naturepedic',
  'NatureZoo',
  'Naturino',
  'Nautica',
  'Neil Barrett',
  'Nerf',
  'New Balance',
  'New Era',
  'New Ray',
  'NEWTON BABY',
  'NG Baby',
  'Nibbling',
  'Nic',
  'Nickelodeon',
  'NIKE',
  'Nikiani',
  'Nina',
  'Nine West',
  'Nintendo',
  'Noa Noa Miniature',
  'Noe & Zoe Berlin',
  'Noël',
  'Nofred',
  'NoJo',
  'Nook Sleep Systems',
  'Nookums',
  'Noppies',
  'Nordstrom',
  'Norsk Dun',
  'Northwest Company',
  'Nova Star',
  'Novelty Poster',
  'Novesta',
  'NUK',
  'Nuna',
  'NUNUNU',
  'NWALKS',
  "O'Neill",
  'OAS',
  'Oball',
  'Obersee',
  'Oeuf',
  'Oii',
  'Oilo',
  'OKBaby',
  'Olababy',
  'Oli & Carol',
  'Oliver & Kids',
  'Oliver & Rain',
  'Olivia Miller',
  'Olivier London',
  'OluKai',
  'OMG Accessories',
  'On the Verge',
  'One Day Parade',
  'One We Like',
  'OppoSuits',
  'Orbit Baby',
  'Original Penguin',
  'Osh Kosh',
  'oskar&ellen',
  'Our Generation',
  'Outerstuff',
  'Outlook',
  'OXO Tot',
  'OYOY',
  'Pabobo',
  'PacaPod',
  'Pacific Play Tents',
  'Padwico',
  'Pam Grace Creations',
  'Papu',
  'Parajumpers',
  'Parkland',
  'Patagonia',
  'Paul Smith Junior',
  'Paw Patrol',
  'Peanuts',
  "Peek Aren't You Curious",
  'Peek Essentials',
  'Peg Perego',
  'Pehr',
  'Pello',
  'Penelope Mack',
  'Penguin Random House',
  'Pepe Jeans',
  'Peppa Pig',
  'Perfect Moment',
  'Perfect Petzzz',
  'Perisphere & Trylon',
  'Perry Ellis',
  'Perry Mackin',
  'Petalia',
  'Petit Bateau',
  'Petit by Sofie Schnoor',
  'Petit Lem',
  'Petit Peony',
  'Petite Olivia',
  'Petunia Pickle Bottom',
  'Phil and Teds',
  'Philips Avent',
  'Piatnik',
  'Pib Baby',
  'Pickle Dot',
  'Pietro Brunelli',
  'Pillow Pets',
  'Pink & Violet',
  'Pippa & Julie',
  'Pippi',
  'PJ Masks',
  'PLAE',
  'Plan Toys',
  'Planet Sox',
  'Plasticine',
  'Platypus Australia',
  'Play Up',
  'Play-Doh',
  'Playforever',
  'Playgro',
  'Playground Pals',
  'PLAYMONSTER',
  'PLH Bows',
  'Plus Plus',
  'Poivre Blanc',
  'Pokemon',
  'Polly Pocket',
  'Polo Ralph Lauren',
  "Pom D'api",
  'POOF',
  'POP Shoes',
  'Popatu',
  'Popular Playthings',
  'Posh Baby & Kids',
  'Potette',
  'Precious Moments',
  'Primigi',
  'Prince Lionheart',
  'Product of the North',
  'Professor Puzzle',
  'Protocol',
  'Psycho Bunny',
  'Puma',
  'PureHeart Organics',
  'Puzzled',
  'Quiksilver',
  'Quinny',
  'R&R Games',
  'Rachel Parcell',
  'Radley London',
  'RAGS',
  'Rainbow',
  'Rainbow Daze',
  'Ralph Lauren',
  'Rampage',
  'Rare Editions',
  'Raspberry Plum',
  'Raspberry Republic',
  'Rätt Start',
  'Ravensburger',
  'Ray-ban',
  'Raybaby',
  'RBO LLC/LITTLE PARTNERS',
  'Re-Cycle-Me',
  'Reaction Kenneth Cole',
  'Rebel James & Charli',
  'Redbox',
  'Reebok',
  'Reef',
  'Reima',
  'Retour',
  'Rhona Sutton',
  'RICE',
  "Ridley's Games Room",
  'Rilakkuma',
  'Ring of Fire',
  'Rip Curl',
  'Rising Sun & Co.',
  'Robeez',
  'Rock Your Kid',
  'RockerMama',
  'Rockland',
  'Romp & Roost',
  'Roomfriends',
  'Roommate',
  'ROSIR',
  'Roxy',
  'Roylco',
  'Rubber Duck',
  'RuffleButts',
  'Rugged Bear',
  'RuggedButts',
  'RVCA',
  'Rylee + Cru',
  'S Rothschild & CO',
  'Safari Ltd.',
  'Safety 1st',
  'Sakroots',
  'Salt Water Sandals by Hoy',
  'Salto',
  'Sam Edelman',
  'Saro',
  'Saucony',
  'Save The Duck',
  'Saxnäs Home',
  'Scamp & Dude',
  'Schleich',
  'Schoenhut',
  'ScienceWiz Products',
  'Scientific Explorer',
  "Scotch R'Belle",
  'Scruff-a-Luvs',
  'Sebra',
  'See Kai Run',
  'seed heritage',
  'Sense',
  'SentoSphere USA',
  'Sequin Hearts',
  'Sesame Street',
  'Shade Critters',
  'Sharper Image',
  'Shepherd',
  'Sherrill Furniture',
  'Shoo Pom',
  'Shopkins',
  'Silly Silas',
  'Silver Cross',
  'Simonetta',
  'SIMPLY NURSERY',
  'Singing Machine',
  'Sitting Bull',
  'SKECHERS',
  'Skip Hop',
  'Sleeping Partners International. INC',
  'Sleepyhead',
  'Slinky',
  'Slumberkins',
  'Småfolk',
  'Small World Toys',
  'Smart Talent',
  'SmartLab Toys',
  'SmartMax',
  'Smoby',
  'Snapper Rock',
  'Snugabye',
  'Snuggle Me',
  'Soft Gallery',
  'Soft Landing',
  'Sole Play',
  'Solly Baby',
  'Solo',
  'Sometime soon',
  'Sons + Daughters',
  'SootheTime',
  'Sophia Webster Mini',
  'Sophie the Giraffe',
  'Sorbet',
  'Sorel',
  'Sorelle Furniture',
  'Sovereign Code',
  'Speechless',
  'Speidel',
  'Sperry',
  'Spin Master Toys',
  'Spirograph',
  'Splash About',
  'Splendid',
  'Sport Squad',
  'Sproet & Sprout',
  'Spyder',
  'Square Root',
  'Squishable',
  'Squishy Mats',
  'Stacy Adams',
  'Stages Learning Materials',
  'Stance',
  'Stanley Jr.',
  'Star Wars',
  'Stella Cove',
  'Stella McCartney Kids',
  'Stem',
  'Stephen Joseph',
  'Steve Madden',
  'Sticky Feet',
  'STIGA',
  'STMT',
  'Stokke',
  'Stonz',
  'Storksak',
  'STOY',
  'Streamline',
  'Stride Rite',
  'Stuart Weitzman',
  'Studio Mercantile',
  'Suavinex',
  'Sub_Urban Riot',
  'Sugar',
  'Sugarfina',
  'Suite Bebe',
  'Suitmeister',
  'Sun Bum',
  'Sunday Afternoons',
  'Sunnylife',
  'Sunuva',
  'Superfit',
  'Superga',
  'Superliving',
  'Swabbies Technologies',
  'Sweet Peas',
  'Sweet Sweet Honey',
  'Sweetlights',
  'SWIM USA',
  'Swimpy',
  'Sylvanian Families',
  'T2 Love',
  'Tadpoles',
  'Tahari Girls',
  'TailorByrd',
  'Tallia',
  'Tangle',
  'Tao&friends',
  'Tasty Tie',
  'Tazio',
  'Tea Collection',
  'Tech Will Save Us',
  'Tedco Toys',
  'Teddykompaniet',
  'Tellkiddo',
  'Ten Sixty Sherman',
  'Tender Leaf Toys',
  'Tendertyme',
  'Tenson',
  'Tenth & Pine',
  'Teva',
  'TFK',
  'TFW',
  'TH Furniture',
  'Thames & Kosmos',
  'The Animals Observatory',
  'The Bonnie Mob',
  'The BRAND',
  'The Honest Company',
  'The Learning Journey',
  'The Little Tailor',
  'The Little White Company',
  'The New Society',
  'The North Face',
  'The Peanutshell',
  'The Purple Cow',
  "The Queen's Treasures",
  'The Tiny Universe',
  'Thermobaby',
  'Thermos',
  'THINX',
  'Thomas & Friends',
  'Threads 4 Thought',
  'Thule',
  'Tiba + Marl',
  'Ticket to Heaven',
  'Timberland',
  'Tinkafu',
  'Tiny Love',
  'Tiny Teethers Designs',
  'Tiny Treasure Doll',
  'TINY TRIBE',
  'tiny twinkle',
  'Tiny Whales',
  'Tinycottons',
  'Tobias & The Bear',
  'Tocoto Vintage',
  'Tom & Teddy',
  'Tom Joule',
  'Tombow',
  'Tommee Tippee',
  'Tommy Hilfiger',
  'Toms',
  'TOMY',
  'Tootsa MacGinty',
  'Totes',
  'ToteSavvy',
  'Tots Fifth Avenue',
  'Touched by Nature',
  'Toy Story',
  'Toysmith',
  'Tractr',
  'Trademark Global',
  'Transformers',
  'Travelon',
  'Travis',
  'Travolution',
  'Treasure & Bond',
  'Trend Lab',
  'Trendy Décor 4U',
  'Tretorn',
  'Trimfit',
  'Trimfoot',
  'Triops, Inc.',
  'Trixxi',
  'Troll',
  'Truly Me',
  'Trumpette',
  'Tsukihoshi',
  'Tucker + Tate',
  'Tuff Tools',
  'Tullsa',
  'Tumi',
  'Tutu Du Monde',
  'TWEE',
  'Tween Bee',
  'TWELVElittle',
  'Twistshake',
  'Ubbi',
  'Udeas',
  'UGG',
  'Ulubulu',
  'UMAGE',
  'Umami',
  'Umbro',
  'Unauthorized',
  'UnbuckleMe',
  'Uncle Milton',
  'Under Armour',
  'Under One Sky',
  'Under the Nile',
  'Unilove',
  'UNiPLAY',
  'United By Blue',
  'United Colors of Benetton',
  'University Games',
  'Univibe',
  'UPPAbaby',
  'Urban Republic',
  'Us Angels',
  'Valtech',
  'Vampirina',
  'Vans',
  'Veer',
  'Veja',
  'Velveteen',
  'Venturelli',
  'Ver de Terre',
  'Vera Bradley',
  'Vera Wang Wedgwood',
  'Versace',
  'Victoria',
  'Victoria Shoes',
  'VIETRI',
  'Viking',
  'Vilah Bloom',
  'Vilebrequin',
  'Vince Camuto',
  'vineyard vines',
  'Vintage Havana',
  'Vintage Summer',
  'Vinter & Bloom',
  'Vogue',
  'Voksi',
  'Volcom',
  'WABA Fun',
  'Walking on Sunshine',
  'Warmies',
  'Warner Brothers',
  'watchitude',
  'Watt & Veke',
  'Wauw Capow',
  'WAWA',
  'WAYB',
  'WE Games',
  'Weathertamer',
  'Weekend House Kids',
  'Western Chief',
  'Westminster Inc.',
  'Wham-o',
  'Wheat',
  'Widgeon',
  'Wiggles 3D',
  'Wildkin',
  'Winning Moves',
  'With You Lockets',
  'WOLF & RITA',
  'Wonder Woman',
  'Wood Little',
  'Wood Wood',
  'World Alive',
  'World Tech Toys',
  'WOW GEAR',
  'Wow Toys',
  'WubbaNub',
  'Wynken',
  'XO Posters',
  'XRAY',
  'Yellow Scope',
  'Yoga Sprout',
  'You! Lingerie',
  'YouGo',
  'Young Soles',
  'Yporqué',
  'Z.A.K. Brand',
  'Zalamoon',
  'Zazu',
  'Zella Girl',
  'Zing Toys',
  'Zoe Organics',
  'ZoLi',
  'ZOOB',
  'Zunie',
]
