export const searchHistory = [{ title: 'search1' }, { title: 'search2' }]

export const datas = [
  { title: 'data1 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
  { title: 'data2 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
  { title: 'abcd 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
  { title: 'efg 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
  { title: 'hij 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
  { title: 'klmn 👶🐣☀️ Boys 18-24mo Spring Play Bundle' },
]

export const dataList = [
  {
    id: 1,
    title: 'data1 👶🐣☀️ Boys 18-24mo Spring Play Bundle',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '90.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    priceOfPerItem: '4.00',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 120,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 121,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 122,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 2,
    title: 'data2 👶🐣☀️ Boys 18-24mo Spring Play Bundle',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '90.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    priceOfPerItem: '4.00',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 120,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 121,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 122,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
]
