export const sellingList = [
  {
    id: '0',
    title: 'my Bundle1',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 1,
    title: 'my Bundle1',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 2,
    title: 'my Bundle2',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 3,
    title: 'my Bundle3',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 4,
    title: 'my Bundle4',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
  {
    id: 5,
    title: 'my Bundle5',
    user: {
      id: '2',
      avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
      fullName: 'amy_192',
      name: 'Sage K.',
      user_description:
        ' I have 2 kids ages 2 and 4. I enjoy cooking, hiking, and \n finding great deals.',
      profile_tags: ['golf', 'tennis', 'cricket'],
    },
    price: '80.00',
    tags: [
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
      '18 Mo',
      '24 Mo',
      'Play',
      'Shirts',
      'Pants',
    ],
    description: 'This is the description of the bundle',
    items: [
      {
        id: 111,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 112,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 113,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 114,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 115,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 116,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 117,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 118,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
      {
        id: 119,
        category: '',
        brand: '',
        condition: '',
        image_front: 'https://pngimg.com/uploads/tshirt/tshirt_PNG5450.png',
        image_back: 'https://www.pngjoy.com/fullpng/e8n4e9a4w8p0l0/',
      },
    ],
    postInfo: {
      mail: '@sagesparkles',
      rating: '4.9',
      time: '4 hrs',
    },
  },
]
